### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by Mardonis** [Starstew/Blackfeather#1]
May I help you with this?

**Comment by Starstew** [comment]
You're welcome to make suggestions, fork the project, etc. Do you have specific areas of the project to which you would like to contribute?

**Comment by Mardonis** [comment]
I thought maybe i could start with linting it first if that may help. The IDE I use is netbeans. This is the first project and first time using github with it. Went through the github tutorial to see how to do commits , changes, and sending it back to be merged but I dont think I did it right. I made some changes on my end and tried sending back to you through the github plugin for netbeans. So looked on the github/blackfeather page and didn't see my commit or any of the changes i had done. Maybe you might know how I can do it? Would really like to help with this if i can please. Thank you.

**Comment by Mardonis** [comment]
Ok I think I know what to do now. Seems like i have missed a step in doing the "Push" so it goes back to your github. So everything is still locally on my machine. I'll try push when i get back home. Thanks.

**Comment by Starstew** [comment]
Linting is a good idea. Just did some with a linter/hinter for Sublime and made updates. It was mostly missing semi-colons, strict equals-ing, and ".foo vs. ['foo']". I converted the "pools" for loot and weapon choices to arrays -- they worked as raw objects, but make more sense as arrays (and pass the linter).

Only thing I didn't change is the dynamic generation of monster and item classes, which the linter doesn't like.

**Comment by Mardonis** [comment]
I'm sorry to be a pain but would you be able to help with this github thing. I have looked through every youtube and text tutorial how how to update but i am just not getting it. I am using netbeans, but I can certainly use sublime. I have used that before. maybe walk me through on how i can send some updates. I have forked your game onto my local side and made some changes. other than that i dont know how i can send them to your github. Thank you.
